#!/bin/bash

mkdir -p new_certs
cd new_certs

openssl genpkey -algorithm RSA -out new_ca.key -aes256 -pkeyopt rsa_keygen_bits:2048
openssl req -key new_ca.key -new -x509 -out new_ca.pem -subj "/C=CZ/ST=South Moravia/L=Brno/O=CESNET z.s.p.o./OU=TMC/CN=example CA/emailAddress=ca@example.org"
openssl genpkey -algorithm RSA -out new_server.key -pkeyopt rsa_keygen_bits:2048
openssl req -key new_server.key -new -out new_server.csr -subj "/C=CZ/ST=South Moravia/L=Brno/O=CESNET z.s.p.o./OU=TMC/CN=example CA/emailAddress=ca@example.org"
openssl x509 -req -in new_server.csr -CA new_ca.pem -CAkey new_ca.key -CAcreateserial -out new_server.crt -days 365
openssl genpkey -algorithm RSA -out new_client.key -pkeyopt rsa_keygen_bits:2048
openssl req -key new_client.key -new -out new_client.csr -subj "/C=CZ/ST=South Moravia/L=Brno/O=CESNET z.s.p.o./OU=TMC/CN=example CA/emailAddress=ca@example.org"
openssl x509 -req -in new_client.csr -CA new_ca.pem -CAkey new_ca.key -CAcreateserial -out new_client.crt -days 365
openssl rsa -in new_server.key -pubout -out new_server.pub
openssl rsa -in new_client.key -pubout -out new_client.pub

rm new_server.csr new_client.csr

echo "Certificates and keys have been generated in the new_certs directory."
