#!/bin/bash

mkdir -p certs
cd certs

#openssl genpkey -algorithm mldsa87 -out ca.key
#openssl req -key ca.key -new -x509 -out ca.pem -subj "/C=CZ/ST=South Moravia/L=Brno/O=CESNET z.s.p.o./OU=TMC/CN=example CA/emailAddress=ca@example.org"

#openssl genpkey -algorithm mldsa87 -out server.key
#openssl req -key server.key -new -out server.csr -subj "/C=CZ/ST=South Moravia/L=Brno/O=CESNET z.s.p.o./OU=TMC/CN=example CA/emailAddress=ca@example.org"
#openssl x509 -req -in server.csr -CA ca.pem -CAkey ca.key -CAcreateserial -out server.crt -days 365

#openssl genpkey -algorithm mldsa87 -out client.key
#openssl req -key client.key -new -out client.csr -subj "/C=CZ/ST=South Moravia/L=Brno/O=CESNET z.s.p.o./OU=TMC/CN=example CA/emailAddress=ca@example.org"
#openssl x509 -req -in client.csr -CA ca.pem -CAkey ca.key -CAcreateserial -out client.crt -days 365

#openssl genpkey -algorithm mldsa87 -out eecert.key
#openssl req -key eecert.key -new -out eecert.csr -subj "/C=CZ/ST=South Moravia/L=Brno/O=CESNET z.s.p.o./OU=TMC/CN=example CA/emailAddress=ca@example.org"
openssl x509 -req -in eecert.csr -CA ca.pem -CAkey ca.key -CAcreateserial -out eecert.pem -days 365

#openssl pkey -in server.key -pubout -out server.pub
#openssl pkey -in client.key -pubout -out client.pub

echo "Certificates and keys PQC have been generated in the certs directory."
